### PR TITLE
export normal vectors from VCM estimators from vol

### PR DESCRIPTION
**Pull request by kerautret**
# PR Description
New tool to estimate normal vectors (using VCM) from digital surface defined in 3D volume. It exports the mesh and the normals vectors
# Checklist

- [ ] Doxygen documentation of the code completed (classes, methods, types, members...)
- [ ] Check if it follows the tools structure described in [CONTRIBUTING.md](https://github.com/DGtal-team/DGtalTools-contrib/blob/master/CONTRIBUTING.md)
- [ ] New entry in the [ChangeLog.md](https://github.com/DGtal-team/DGtalTools-contrib/blob/master/ChangeLog.md) added.
- [ ] Update the readme with potentially a screenshot of the tools if it applies. 
- [ ] No warning raised in Debug ```cmake``` mode (otherwise, Travis C.I. will fail).
- [ ] All continuous integration tests pass (Github Actions & appveyor).

### CODE REVIEW

**Comment by dcoeurjo** [comment]
There is no VCM based normal vector +export in DGtal?

**Comment by kerautret** [comment]
> There is no VCM based normal vector +export in DGtal?

yes there is https://github.com/DGtal-team/DGtalTools/blob/master/estimators/vol2normalField.cpp 
That can be used but not use VCM for now, it was a step before migrate it in DGtalTools..

**Comment by dcoeurjo** [comment]
I see, there is also the shortcut https://dgtal-team.github.io/doc-nightly/classDGtal_1_1ShortcutsGeometry.html#afc9c5cfff9a32d072e2486ab491b269f

**Comment by kerautret** [comment]
> I see, there is also the shortcut https://dgtal-team.github.io/doc-nightly/classDGtal_1_1ShortcutsGeometry.html#afc9c5cfff9a32d072e2486ab491b269f
Yes I forget, the Jaco code was before the shortcut  ;)

**Comment by kerautret** [comment]
thanks

**Comment by kerautret** [comment]
Merging, I make an issue to use shortcut as discussed.

**Pull request merged**
