### PR TITLE
first progs

### PR DESCRIPTION
**Pull request by kerautret**

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Could you please enable Travis for the contrib ? (And add the script) ?

**Comment by kerautret** [comment]
yes but it will fail (until the PR of the AlphaThickSegments) ;à

**Comment by kerautret** [comment]
done for travis ;)

**Comment by kerautret** [comment]
@dcoeurjo current PR working with travis and master merged on my remote

**Comment by dcoeurjo** [comment]
Yep I see.. I'll merge your DGtal PR first I think.

**Comment by dcoeurjo** [comment]
can you please update your script to fetch DGtal and not your clone ?

**Comment by kerautret** [comment]
ok so I just comment cmakelist for meaningfulThickness prof which use ScaleProfile and Statistics ;)

**Comment by kerautret** [comment]
done

**Comment by dcoeurjo** [comment]
Ah ok... I thought you just needed Alphathick :)
I'll review the pending PR this WE

**Comment by dcoeurjo** [comment]
ok merging this one, we'll see for the DGtal pending PRs

**Comment by dcoeurjo** [comment]
thanks, BTW ;)

**Comment by dcoeurjo** [comment]
Just a comment: to avoid a big mess in the subfolders, I think we should enhance the README.md to clearly describe each tool and CLI.

**Comment by kerautret** [comment]
yes agree I will add it ;)

**Pull request merged**
